# Generated by Django 3.1.2 on 2021-12-04 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=13)),
                ('paginas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('desc_corta', models.CharField(default='Sin reseña', max_length=200, verbose_name='Descripcion corta')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
